ERROR - 2022-10-04 03:59:48 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\SIPETIK_BAJA\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\SIPETIK_BAJA\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', '', '', '', 3306, '', 0)
#1 C:\xampp\htdocs\SIPETIK_BAJA\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\SIPETIK_BAJA\vendor\codeigniter4\framework\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\SIPETIK_BAJA\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ak...', Array, false)
#4 C:\xampp\htdocs\SIPETIK_BAJA\vendor\codeigniter4\framework\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\SIPETIK_BAJA\vendor\codeigniter4\framework\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\SIPETIK_BAJA\vendor\codeigniter4\framework\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\SIPETIK_BAJA\vendor\codeigniter4\framework\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\SIPETIK_BAJA\app\Controllers\user\FunctionUser.php(91): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\SIPETIK_BAJA\vendor\codeigniter4\framework\system\CodeIgniter.php(907): App\Controllers\user\FunctionUser->Register_User()
#10 C:\xampp\htdocs\SIPETIK_BAJA\vendor\codeigniter4\framework\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\user\FunctionUser))
#11 C:\xampp\htdocs\SIPETIK_BAJA\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\SIPETIK_BAJA\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\SIPETIK_BAJA\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\SIPETIK_BAJA\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\SIPETIK_BAJA\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\SIPETIK_BAJA\vendor\codeigniter4\framework\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\SIPETIK_BAJA\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ak...', Array, false)
#3 C:\xampp\htdocs\SIPETIK_BAJA\vendor\codeigniter4\framework\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#4 C:\xampp\htdocs\SIPETIK_BAJA\vendor\codeigniter4\framework\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#5 C:\xampp\htdocs\SIPETIK_BAJA\vendor\codeigniter4\framework\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, false)
#6 C:\xampp\htdocs\SIPETIK_BAJA\vendor\codeigniter4\framework\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#7 C:\xampp\htdocs\SIPETIK_BAJA\app\Controllers\user\FunctionUser.php(91): CodeIgniter\BaseModel->save(Array)
#8 C:\xampp\htdocs\SIPETIK_BAJA\vendor\codeigniter4\framework\system\CodeIgniter.php(907): App\Controllers\user\FunctionUser->Register_User()
#9 C:\xampp\htdocs\SIPETIK_BAJA\vendor\codeigniter4\framework\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\user\FunctionUser))
#10 C:\xampp\htdocs\SIPETIK_BAJA\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\SIPETIK_BAJA\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\SIPETIK_BAJA\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#13 {main}
CRITICAL - 2022-10-04 03:59:48 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `akun_user` (`username`, `password`, `email`, `nama_pelanggan`, `nomor_hp_pelanggan`) VALUES (:username:, :password:, :email:, :nama_pelanggan:, :nomor_hp_pelanggan:)', [...], false)
 3 SYSTEMPATH\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
 4 SYSTEMPATH\BaseModel.php(738): CodeIgniter\Model->doInsert([...])
 5 SYSTEMPATH\Model.php(667): CodeIgniter\BaseModel->insert([...], false)
 6 SYSTEMPATH\BaseModel.php(658): CodeIgniter\Model->insert([...], false)
 7 APPPATH\Controllers\user\FunctionUser.php(91): CodeIgniter\BaseModel->save([...])
 8 SYSTEMPATH\CodeIgniter.php(907): App\Controllers\user\FunctionUser->Register_User()
 9 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\user\FunctionUser))
10 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
